server:
  port: 8081

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.2.155:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
